In [23]:
import math

In [24]:
# example dataset 
# let's say we have a dataset with two classes , A and B
# suppose in a dataset of 10 elements, 4 are class A and 6 are of class B

# number of elements in each class 

n_A = 4
n_B = 6
total = n_A + n_B

In [25]:
# let's calculate the proportions
p_A = n_A / total
p_B = n_B / total

# print the proportions
print(f"Proportion of class A: {p_A}")
print(f"Proportion of class B: {p_B}")

Proportion of class A: 0.4
Proportion of class B: 0.6

In [26]:
# Entopy calculation
# Enttropy is a measure of uncertainty

entropy = - (p_A * math.log2(p_A) + p_B * math.log2(p_B))
print(f"Entropy: {entropy}")

Entropy: 0.9709505944546686

In [27]:
# gini impurity calculation
# gini impurity is a measure of misclassification
gini_impurity = 1 - (p_A**2 + p_B**2)
print(f"Gini Impurity: {gini_impurity}")

Gini Impurity: 0.48

In [28]:
# inofrmation gain
# Assuming a split on some feature divides the dataset into two subsets
# subset 1: 2 elements of A, 3 of B
# subset 2: 2 elements of A, 3 of B
# entropy and size for each subset
n1_A, n1_B = 2, 3
n2_A, n2_B = 2, 3

p_1_A = n1_A / (n1_A + n1_B)
p_1_B = n1_B / (n1_A + n1_B)
entropy_1 = - (p_1_A * math.log2(p_1_A) + p_1_B * math.log2(p_1_B)) if p_1_A and p_1_B else 0

p_2_A = n2_A / (n2_A + n2_B)
p_2_B = n2_B / (n2_A + n2_B)
entropy_2 = - (p_2_A * math.log2(p_2_A) + p_2_B * math.log2(p_2_B)) if p_2_A and p_2_B else 0

information_gain = entropy - ((n1_A + n1_B) / total * entropy_1 + (n2_A + n2_B) / total * entropy_2)  

print(f"Information Gain: {information_gain}")

Information Gain: 0.0

-----------------
# Decision Tree Example in python

In [29]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

In [30]:
# load the dataset 
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [31]:
# drop deck colum
df.drop('deck', axis=1, inplace=True)

# impute missing values of age, and fear using median
imputer = SimpleImputer(strategy='median')
df[['age', 'fare']] = imputer.fit_transform(df[['age', 'fare']])

# impute missing values of embarked and embark_town using mode
imputer_mode = SimpleImputer(strategy='most_frequent')
df[['embarked', 'embark_town']] = imputer_mode.fit_transform(df[['embarked', 'embark_town']])

In [32]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [33]:
# encode the categorical and object variables using forloop and labelencoder
label_encoders = {}
for col in df.columns:
    if df[col].dtype == 'object' or df[col].dtype.name == 'category':
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le

In [34]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [35]:
# split the data into X and y 
X = df.drop('survived', axis=1)
y = df['survived']
# split the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
# create and train the model with pred 
model = DecisionTreeClassifier(criterion='entropy', random_state=42)
model.fit(X_train, y_train)

# predict the model 
y_pred = model.predict(X_test)

In [37]:
# evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[105   0]
 [  0  74]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00        74

    accuracy                           1.00       179
   macro avg       1.00      1.00      1.00       179
weighted avg       1.00      1.00      1.00       179

In [38]:
# # save the decision tree classifier
# from sklearn.tree import export_graphviz
# export_graphviz(model, out_file='./save models/decision_tree_01.dot',feature_names=X.columns, filled=True, rounded=True)

In [42]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(criterion='friedman_mse', random_state=42)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
print(f'r2_score: {r2_score(y_test, y_pred)}')
print(f'mean_squared_error: {mean_squared_error(y_test, y_pred)}')
print(f'mean_absolute_error: {mean_absolute_error(y_test, y_pred)}')

r2_score: 1.0
mean_squared_error: 0.0
mean_absolute_error: 0.0