# Plotly Data Visualization

In [2]:
# install plotly
!pip install -U plotly kaleido

Requirement already satisfied: plotly in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (6.3.1)
Requirement already satisfied: kaleido in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (1.1.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from plotly) (2.7.0)
Requirement already satisfied: packaging in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from plotly) (25.0)
Requirement already satisfied: choreographer>=1.0.10 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from kaleido) (1.1.2)
Requirement already satisfied: logistro>=1.0.8 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from kaleido) (1.1.0)
Requirement already satisfied: orjson>=3.10.15 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from kaleido) (3.11.3)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from kaleido) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from choreographer>=1.0.10->kaleido) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from pytest-timeout>=2.4.0->kaleido) (8.4.2)
Requirement already satisfied: colorama>=0.4 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (0.4.6)
Requirement already satisfied: iniconfig>=1 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.1.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in c:\users\nasik\miniconda3\envs\python_eda\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.19.2)

In [3]:
# import libraries
import pandas as pd
import plotly.express as px
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
name = ['Aammar', 'Humza', 'Arshad']
height = [5.8, 5.9, 5.7]

# import library
import plotly.express as px

# create a plot (line chart)
fig = px.bar(x=name, y=height, title='Height of Students')
# show the figure
fig.show()


# save the plot in png file



# save as standalone html file
fig.write_html("plot.html")

In [5]:
fig.write_image("plot.png")

# plots on titanic dataset

In [6]:
# import dataset 
df = sns.load_dataset('titanic')
# check the dataset
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [7]:
# scatter plot 
fig = px.scatter(df, x='age', y='fare', title='plot of age vs fare')
fig.show()

In [ ]:
# scatter plot 
df.dropna(inplace=True)
fig = px.scatter(df, x='age', y='fare', color='sex', size='fare',title='plot of age vs fare')
fig.show()
fig.write_image("plot_2.png", scale=3) # how to save in 300dpi

In [14]:
import plotly.graph_objects as go

fig = go.Figure(data=go.Scatter(x=[1, 2, 3], y=[4, 5, 6]))
fig.show()

In [17]:
# coustomize the plot

fig.update_layout(
    title = 'Line Plot of dummy data ',
    xaxis = {'title': 'Number'},
    yaxis = {'title': 'Value'},
    showlegend = True
)

In [18]:
# heatmaps in plotly

data = np.random.randn(20, 20)
heatmap = go.Heatmap(z=data)

fig = go.Figure(data=heatmap)
fig.show()

In [20]:
# heatmap on corr of titanic dataset of age and fare using plotly

fig = px.imshow(df[['age', 'fare']].corr())
fig.show()

In [21]:
# iris 

iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [23]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [26]:
# heatmapon corr of iris dataset of sepal_length and sepal_width using plotly

fig = px.imshow(iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].corr())
fig.show()